### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by martoio** [Kkolya/prj-rev-bwfs-dasmoto#4]
Interesting touch with the navigation! One thing to consider is that when using a list to make your navigation, you should try to remove the bullet points on the left:
![image](https://user-images.githubusercontent.com/8990516/52607922-f2e45600-2e2c-11e9-9ea2-bd36dd2371af.png)

Also, a list will have some padding by default because of the bullet points. Try the following:
```css
ul{
    list-style-type: none;
    margin: 0;
    padding: 0;
}
```

Of course, try to get the selector a bit more specific than that to fit your use case (something like `nav ul` ought to do it).
